---
service_name: xapp
version: 0
gui_width: 800
gui_height: 600
build_packages: []
run_packages: []
stage_files: []
public_vnc_port: 5900
public_websockify_port: 6080
xdisplay: 0
executable: xapp
restart_policy: unless-stopped
container_state: stopped
