---
- hosts: all
  tasks:
  - name: Install prerequisites for building PHD2
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - build-essential
      - git
      - cmake
      - pkg-config
      - libwxgtk3.0-dev
      - wx-common
      - wx3.0-i18n
      - libindi-dev
      - libnova-dev
      - zlib1g-dev
    become: true

  - name: Download PHD2
    git: >
      repo=https://github.com/OpenPHDGuiding/phd2.git
      dest=/home/vagrant/phd2
      version=f8c684a0d94a38e924663561fafe1c0769e89351
      depth=1

  - name: Create tmp directory for PHD2 compilation
    file: path=/home/vagrant/phd2/tmp state=directory

  - name: Configure PHD2
    command: cmake .. chdir=/home/vagrant/phd2/tmp creates=/home/vagrant/phd2/tmp/Makefile

  - name: Build PHD2
    command: make chdir=/home/vagrant/phd2/tmp creates=/home/vagrant/phd2/tmp/phd2

  - name: Install PHD2
    command: make install chdir=/home/vagrant/phd2/tmp creates=/usr/local/bin/phd2
    become: true

  - name: Install virtual graphical environment
    apt: name={{item}} state=installed
    with_items:
      - xvfb
      - x11vnc
    become: true

  - name: Create Virtual X frame buffer service for PHD2
    template: src=templates/Xvfb_phd2.service.j2 dest=/etc/systemd/system/Xvfb_phd2.service mode=0644 owner=root group=root
    become: true

  - name: Create VNC service for PHD2
    template: src=templates/x11vnc_phd2.service.j2 dest=/etc/systemd/system/x11vnc_phd2.service mode=0644 owner=root group=root
    become: true

  - name: Create PHD2 service
    template: src=templates/phd2.service.j2 dest=/etc/systemd/system/phd2.service mode=0644 owner=root group=root
    become: true

  - name: Enable and start Virtual X frame buffer service for PHD2
    service: name=Xvfb_phd2 enabled=yes state=started
    become: true

  - name: Enable and start VNC service for PHD2
    service: name=x11vnc_phd2 enabled=yes state=started
    become: true

  - name: Enable and start PHD2 service
    service: name=phd2 enabled=yes state=started
    become: true
