---
- hosts: all
  tasks:
  - name: Install prerequisites for building PHD2
    apt: name={{item}} state=installed
    with_items:
      - build-essential
      - git
      - cmake
      - pkg-config
      - libwxgtk3.0-dev
      - wx-common
      - wx3.0-i18n
      - libindi-dev
      - libnova-dev
      - zlib1g-dev
    become: true

  - name: Download PHD2
    git: >
      repo=https://github.com/OpenPHDGuiding/phd2.git
      dest=/home/vagrant/phd2
      version=f8c684a0d94a38e924663561fafe1c0769e89351
      depth=1

  - name: Create tmp directory for PHD2 compilation
    file: path=/home/vagrant/phd2/tmp state=directory

  - name: Configure PHD2
    command: cmake .. chdir=/home/vagrant/phd2/tmp creates=/home/vagrant/phd2/tmp/Makefile

  - name: Build PHD2
    command: make chdir=/home/vagrant/phd2/tmp creates=/home/vagrant/phd2/tmp/phd2

  - name: Install PHD2
    command: make install chdir=/home/vagrant/phd2/tmp creates=/usr/local/bin/phd2
    become: true

  - name: Install virtual graphical environment
    apt: name={{item}} state=installed
    with_items:
      - xvfb
      - x11vnc
    become: true

  - name: Create virtual display
    shell: nohup Xvfb :1 -screen 0 800x600x16 &

  - name: Launch VNC server
    shell: x11vnc -display :1 -bg

  - name: Launch PHD2
    shell: DISPLAY=:1 nohup phd2 &
